Description: Group for ACE training (through NIAID/NIH) 
Department: Bioinformatics and Computational Biosciences Branch (BCBB)
FieldOfScience: Training
Organization: NIAID/NIH
PIName: Mariam Quiñones 

Sponsor:
  CampusGrid:
    Name: OSG Connect
InstitutionID: 'https://osg-htc.org/iid/451cgt72wj62'
